"""Full 99-achievement master recovered from the TB project
(repository.org/WkmKsk/TB, v1.4.18). Reference data only: the server
still settles only the ClearChapter rows via achievement_data.py.
The other unlock types are client-local counters, kept here so the
list matches what the client UI shows and future extensions have
authoritative values.

Each row mirrors the client's AchivementInfo schema."""

from __future__ import annotations

ACHIEVEMENT_MASTER: tuple[dict, ...] = (
    {"id": 1, "key": "ClearChapter5", "unlockType": "ClearChapter", "unlockValues": (5, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 2, "key": "ClearChapter10", "unlockType": "ClearChapter", "unlockValues": (10, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 3, "key": "ClearChapter15", "unlockType": "ClearChapter", "unlockValues": (15, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 4, "key": "ClearChapter20", "unlockType": "ClearChapter", "unlockValues": (20, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 5, "key": "ClearChapter25", "unlockType": "ClearChapter", "unlockValues": (25, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 6, "key": "ClearChapter30", "unlockType": "ClearChapter", "unlockValues": (30, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 7, "key": "ClearChapter35", "unlockType": "ClearChapter", "unlockValues": (35, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 8, "key": "ClearChapter40", "unlockType": "ClearChapter", "unlockValues": (40, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1}, {"type": "Item", "id": 50, "num": 1},)},
    {"id": 9, "key": "CharaLevel20", "unlockType": "CharaLevel", "unlockValues": (20, 6, 0,), "presents": ({"type": "Item", "id": 18, "num": 1}, {"type": "Item", "id": 19, "num": 1}, {"type": "Item", "id": 20, "num": 1}, {"type": "Item", "id": 21, "num": 1},)},
    {"id": 10, "key": "CharaLevel30", "unlockType": "CharaLevel", "unlockValues": (30, 6, 0,), "presents": ({"type": "Item", "id": 18, "num": 1}, {"type": "Item", "id": 19, "num": 1}, {"type": "Item", "id": 20, "num": 1}, {"type": "Item", "id": 21, "num": 1},)},
    {"id": 11, "key": "CharaLevel40", "unlockType": "CharaLevel", "unlockValues": (40, 6, 0,), "presents": ({"type": "Item", "id": 22, "num": 1}, {"type": "Item", "id": 23, "num": 1}, {"type": "Item", "id": 24, "num": 1}, {"type": "Item", "id": 25, "num": 1},)},
    {"id": 12, "key": "CharaLevel50", "unlockType": "CharaLevel", "unlockValues": (50, 6, 0,), "presents": ({"type": "Item", "id": 22, "num": 1}, {"type": "Item", "id": 23, "num": 1}, {"type": "Item", "id": 24, "num": 1}, {"type": "Item", "id": 25, "num": 1},)},
    {"id": 13, "key": "CharaLevel60", "unlockType": "CharaLevel", "unlockValues": (60, 6, 0,), "presents": ({"type": "Item", "id": 22, "num": 1}, {"type": "Item", "id": 23, "num": 1}, {"type": "Item", "id": 24, "num": 1}, {"type": "Item", "id": 25, "num": 1},)},
    {"id": 14, "key": "CharaLevel70", "unlockType": "CharaLevel", "unlockValues": (70, 6, 0,), "presents": ({"type": "Item", "id": 26, "num": 1}, {"type": "Item", "id": 27, "num": 1}, {"type": "Item", "id": 28, "num": 1}, {"type": "Item", "id": 29, "num": 1},)},
    {"id": 15, "key": "CharaLevel80", "unlockType": "CharaLevel", "unlockValues": (80, 6, 0,), "presents": ({"type": "Item", "id": 26, "num": 1}, {"type": "Item", "id": 27, "num": 1}, {"type": "Item", "id": 28, "num": 1}, {"type": "Item", "id": 29, "num": 1},)},
    {"id": 16, "key": "CharaLevel90", "unlockType": "CharaLevel", "unlockValues": (90, 6, 0,), "presents": ({"type": "Item", "id": 26, "num": 1}, {"type": "Item", "id": 27, "num": 1}, {"type": "Item", "id": 28, "num": 1}, {"type": "Item", "id": 29, "num": 1},)},
    {"id": 17, "key": "CharaJob2x3", "unlockType": "CharaJob", "unlockValues": (2, 3, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 18, "key": "CharaJob2x6", "unlockType": "CharaJob", "unlockValues": (2, 6, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 19, "key": "CharaJob2x12", "unlockType": "CharaJob", "unlockValues": (2, 12, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 20, "key": "CharaJob2x24", "unlockType": "CharaJob", "unlockValues": (2, 24, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 21, "key": "CharaJob2x36", "unlockType": "CharaJob", "unlockValues": (2, 36, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 22, "key": "CharaJob3x3", "unlockType": "CharaJob", "unlockValues": (3, 3, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 23, "key": "CharaJob3x6", "unlockType": "CharaJob", "unlockValues": (3, 6, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 24, "key": "CharaJob3x12", "unlockType": "CharaJob", "unlockValues": (3, 12, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 25, "key": "CharaJob3x24", "unlockType": "CharaJob", "unlockValues": (3, 24, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 26, "key": "CharaJob3x36", "unlockType": "CharaJob", "unlockValues": (3, 36, 0,), "presents": ({"type": "Item", "id": 50, "num": 1}, {"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 56, "num": 1},)},
    {"id": 27, "key": "HumanCollector1", "unlockType": "SpeciesNum", "unlockValues": (1, 5, 0,), "presents": ({"type": "Item", "id": 1, "num": 10}, {"type": "Item", "id": 2, "num": 10},)},
    {"id": 28, "key": "HumanCollector2", "unlockType": "SpeciesNum", "unlockValues": (1, 10, 0,), "presents": ({"type": "Item", "id": 1, "num": 10}, {"type": "Item", "id": 2, "num": 10},)},
    {"id": 29, "key": "HumanCollector3", "unlockType": "SpeciesNum", "unlockValues": (1, 20, 0,), "presents": ({"type": "Item", "id": 1, "num": 10}, {"type": "Item", "id": 2, "num": 10},)},
    {"id": 30, "key": "LizardCollector1", "unlockType": "SpeciesNum", "unlockValues": (2, 5, 0,), "presents": ({"type": "Item", "id": 3, "num": 10}, {"type": "Item", "id": 4, "num": 10},)},
    {"id": 31, "key": "LizardCollector2", "unlockType": "SpeciesNum", "unlockValues": (2, 10, 0,), "presents": ({"type": "Item", "id": 3, "num": 10}, {"type": "Item", "id": 4, "num": 10},)},
    {"id": 32, "key": "LizardCollector3", "unlockType": "SpeciesNum", "unlockValues": (2, 20, 0,), "presents": ({"type": "Item", "id": 3, "num": 10}, {"type": "Item", "id": 4, "num": 10},)},
    {"id": 33, "key": "BeastCollector1", "unlockType": "SpeciesNum", "unlockValues": (3, 5, 0,), "presents": ({"type": "Item", "id": 5, "num": 10}, {"type": "Item", "id": 6, "num": 10},)},
    {"id": 34, "key": "BeastCollector2", "unlockType": "SpeciesNum", "unlockValues": (3, 10, 0,), "presents": ({"type": "Item", "id": 5, "num": 10}, {"type": "Item", "id": 6, "num": 10},)},
    {"id": 35, "key": "BeastCollector3", "unlockType": "SpeciesNum", "unlockValues": (3, 20, 0,), "presents": ({"type": "Item", "id": 5, "num": 10}, {"type": "Item", "id": 6, "num": 10},)},
    {"id": 36, "key": "StoneCollector1", "unlockType": "SpeciesNum", "unlockValues": (4, 5, 0,), "presents": ({"type": "Item", "id": 7, "num": 10}, {"type": "Item", "id": 8, "num": 10},)},
    {"id": 37, "key": "StoneCollector2", "unlockType": "SpeciesNum", "unlockValues": (4, 10, 0,), "presents": ({"type": "Item", "id": 7, "num": 10}, {"type": "Item", "id": 8, "num": 10},)},
    {"id": 38, "key": "StoneCollector3", "unlockType": "SpeciesNum", "unlockValues": (4, 20, 0,), "presents": ({"type": "Item", "id": 7, "num": 10}, {"type": "Item", "id": 8, "num": 10},)},
    {"id": 39, "key": "WildCollector1", "unlockType": "SpeciesNum", "unlockValues": (6, 5, 0,), "presents": ({"type": "Item", "id": 9, "num": 10}, {"type": "Item", "id": 10, "num": 10}, {"type": "Item", "id": 11, "num": 10}, {"type": "Item", "id": 12, "num": 10},)},
    {"id": 40, "key": "WildCollector2", "unlockType": "SpeciesNum", "unlockValues": (6, 10, 0,), "presents": ({"type": "Item", "id": 13, "num": 10}, {"type": "Item", "id": 14, "num": 10}, {"type": "Item", "id": 15, "num": 10}, {"type": "Item", "id": 16, "num": 10},)},
    {"id": 41, "key": "WildCollector3", "unlockType": "SpeciesNum", "unlockValues": (6, 20, 0,), "presents": ({"type": "Item", "id": 18, "num": 1}, {"type": "Item", "id": 19, "num": 1}, {"type": "Item", "id": 20, "num": 1}, {"type": "Item", "id": 21, "num": 1},)},
    {"id": 42, "key": "DragonCollector1", "unlockType": "SpeciesNum", "unlockValues": (7, 10, 0,), "presents": ({"type": "Item", "id": 89, "num": 15}, {"type": "Item", "id": 90, "num": 15},)},
    {"id": 43, "key": "SummonLevel1", "unlockType": "SummonLevel", "unlockValues": (1, 5, 0,), "presents": ({"type": "Item", "id": 59, "num": 1}, {"type": "Item", "id": 60, "num": 1},)},
    {"id": 44, "key": "SummonLevel2", "unlockType": "SummonLevel", "unlockValues": (2, 5, 0,), "presents": ({"type": "Item", "id": 59, "num": 1}, {"type": "Item", "id": 60, "num": 1},)},
    {"id": 45, "key": "SummonLevel3", "unlockType": "SummonLevel", "unlockValues": (3, 5, 0,), "presents": ({"type": "Item", "id": 59, "num": 1}, {"type": "Item", "id": 60, "num": 1},)},
    {"id": 46, "key": "SwordParty1", "unlockType": "ArmsLevel", "unlockValues": (25, 3, 1,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 47, "key": "SwordParty2", "unlockType": "ArmsLevel", "unlockValues": (55, 3, 1,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 48, "key": "SwordParty3", "unlockType": "ArmsLevel", "unlockValues": (85, 3, 1,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 49, "key": "SpearParty1", "unlockType": "ArmsLevel", "unlockValues": (25, 3, 2,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 50, "key": "SpearParty2", "unlockType": "ArmsLevel", "unlockValues": (55, 3, 2,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 51, "key": "SpearParty3", "unlockType": "ArmsLevel", "unlockValues": (85, 3, 2,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 52, "key": "ArrowParty1", "unlockType": "ArmsLevel", "unlockValues": (25, 3, 3,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 53, "key": "ArrowParty2", "unlockType": "ArmsLevel", "unlockValues": (55, 3, 3,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 54, "key": "ArrowPartyt3", "unlockType": "ArmsLevel", "unlockValues": (85, 3, 3,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 55, "key": "WandParty1", "unlockType": "ArmsLevel", "unlockValues": (25, 3, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 56, "key": "WandParty2", "unlockType": "ArmsLevel", "unlockValues": (55, 3, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 57, "key": "WandParty3", "unlockType": "ArmsLevel", "unlockValues": (85, 3, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 58, "key": "SkillMaster1", "unlockType": "CharaSkillNum", "unlockValues": (12, 6, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 59, "key": "SkillMaster2", "unlockType": "CharaSkillNum", "unlockValues": (12, 12, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 60, "key": "SkillMaster3", "unlockType": "CharaSkillNum", "unlockValues": (12, 20, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 61, "key": "SkillMaster4", "unlockType": "CharaSkillNum", "unlockValues": (12, 20, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 62, "key": "ExpGatherer", "unlockType": "GatheringExp", "unlockValues": (300000, 1000, 2,), "presents": ({"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 53, "num": 1},)},
    {"id": 63, "key": "CoinGatherer", "unlockType": "GatheringCoin", "unlockValues": (10000, 1003, 2,), "presents": ({"type": "Item", "id": 56, "num": 1}, {"type": "Item", "id": 53, "num": 1},)},
    {"id": 64, "key": "ItemGatherer", "unlockType": "GatheringItem", "unlockValues": (70, 1004, 2,), "presents": ({"type": "Item", "id": 54, "num": 1}, {"type": "Item", "id": 53, "num": 1},)},
    {"id": 65, "key": "GirlsTalk", "unlockType": "GenderParty", "unlockValues": (2, 10, 10,), "presents": ({"type": "Energy", "id": 0, "num": 2},)},
    {"id": 66, "key": "SpeedStar", "unlockType": "SpeedClear", "unlockValues": (5, 20, 1,), "presents": ({"type": "Energy", "id": 0, "num": 2},)},
    {"id": 67, "key": "BeastMaster", "unlockType": "SpeciesParty", "unlockValues": (6, 20, 1,), "presents": ({"type": "Energy", "id": 0, "num": 2},)},
    {"id": 68, "key": "Freedom", "unlockType": "CoopFreeNum", "unlockValues": (-1, 30, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 69, "key": "Friendly", "unlockType": "CoopFriendNum", "unlockValues": (-1, 30, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 70, "key": "Ownership", "unlockType": "CoopFreeNum", "unlockValues": (0, 50, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 71, "key": "Supporter", "unlockType": "CoopFreeNum", "unlockValues": (1, 50, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 72, "key": "Speedy", "unlockType": "CoopSimpleNum", "unlockValues": (-1, 30, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 73, "key": "Prize1", "unlockType": "CoopPrize", "unlockValues": (20, 0, 0,), "presents": ({"type": "Item", "id": 81, "num": 2},)},
    {"id": 74, "key": "VsMaster", "unlockType": "VsFreeNum", "unlockValues": (-1, 100, 0,), "presents": ({"type": "Title", "id": 1, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 75, "key": "VsMaster2", "unlockType": "VsFreeNum", "unlockValues": (-1, 300, 0,), "presents": ({"type": "Title", "id": 2, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 76, "key": "VsMaster3", "unlockType": "VsFreeNum", "unlockValues": (-1, 500, 0,), "presents": ({"type": "Title", "id": 3, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 77, "key": "FriendBattler", "unlockType": "VsFriendNum", "unlockValues": (-1, 20, 0,), "presents": ({"type": "Title", "id": 0, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 78, "key": "VsKiller", "unlockType": "VsFreeWin", "unlockValues": (-1, 50, 0,), "presents": ({"type": "Title", "id": 4, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 79, "key": "VsKiller2", "unlockType": "VsFreeWin", "unlockValues": (-1, 150, 0,), "presents": ({"type": "Title", "id": 5, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 80, "key": "VsKiller3", "unlockType": "VsFreeWin", "unlockValues": (-1, 250, 0,), "presents": ({"type": "Title", "id": 6, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 81, "key": "FriendKiller", "unlockType": "VsFriendWin", "unlockValues": (-1, 50, 0,), "presents": ({"type": "Title", "id": 0, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 82, "key": "Striker", "unlockType": "VsFreeConsectiveWin", "unlockValues": (-1, 3, 0,), "presents": ({"type": "Title", "id": 7, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 83, "key": "Striker2", "unlockType": "VsFreeConsectiveWin", "unlockValues": (-1, 5, 0,), "presents": ({"type": "Title", "id": 8, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 84, "key": "Striker3", "unlockType": "VsFreeConsectiveWin", "unlockValues": (-1, 10, 0,), "presents": ({"type": "Title", "id": 9, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 85, "key": "FriendStriker", "unlockType": "VsFriendConsectiveWin", "unlockValues": (-1, 20, 0,), "presents": ({"type": "Title", "id": 0, "num": 1}, {"type": "Energy", "id": 0, "num": 1},)},
    {"id": 86, "key": "PostTwitter1", "unlockType": "SocialPost", "unlockValues": (0, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 87, "key": "PostLine1", "unlockType": "SocialPost", "unlockValues": (2, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 88, "key": "Temp1", "unlockType": "SocialPost", "unlockValues": (0, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 89, "key": "Temp2", "unlockType": "SocialPost", "unlockValues": (0, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 90, "key": "ExpGatherer2", "unlockType": "GatheringExp", "unlockValues": (500000, 1000, 3,), "presents": ({"type": "Item", "id": 55, "num": 1}, {"type": "Item", "id": 53, "num": 1},)},
    {"id": 91, "key": "CoinGatherer2", "unlockType": "GatheringCoin", "unlockValues": (15000, 1003, 3,), "presents": ({"type": "Item", "id": 56, "num": 1}, {"type": "Item", "id": 53, "num": 1},)},
    {"id": 92, "key": "ItemGatherer2", "unlockType": "GatheringItem", "unlockValues": (80, 1004, 3,), "presents": ({"type": "Item", "id": 54, "num": 1}, {"type": "Item", "id": 53, "num": 1},)},
    {"id": 93, "key": "Prize2", "unlockType": "CoopPrize", "unlockValues": (50, 0, 0,), "presents": ({"type": "Item", "id": 81, "num": 5},)},
    {"id": 94, "key": "Survey1", "unlockType": "Survey", "unlockValues": (1, 0, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 95, "key": "SpecialQuest9010", "unlockType": "SpecialQuest", "unlockValues": (9010, 3, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 96, "key": "SpecialQuest9011", "unlockType": "SpecialQuest", "unlockValues": (9011, 3, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 97, "key": "SpecialQuest9012", "unlockType": "SpecialQuest", "unlockValues": (9012, 3, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 98, "key": "SpecialQuest9013", "unlockType": "SpecialQuest", "unlockValues": (9013, 3, 0,), "presents": ({"type": "Energy", "id": 0, "num": 1},)},
    {"id": 0, "key": "", "unlockType": "ClearChapter", "unlockValues": (0, 0, 0,), "presents": ()},
)

ACHIEVEMENT_MASTER_COUNT = len(ACHIEVEMENT_MASTER)