"""Item ID -> display name map, recovered from the reTB project
(codeberg.org/WkmKsk/reTB, v1.4.18). Reference data for logging and
documenting Luck chest rewards; 181 items."""

from __future__ import annotations

ITEM_NAMES: dict[int, str] = {
    1: "Serenity Shoot",
    2: "Wisdom Flower",
    3: "Benevolent Fang",
    4: "Tail of Insight",
    5: "Claw of Fate",
    6: "Pelt of Knowledge",
    7: "Forlorn Stone",
    8: "Shell of Madness",
    9: "Terra Swordsteel",
    10: "Terra Spearbronze",
    11: "Terra Bowstring",
    12: "Terra Staffwood",
    13: "Fire Ring",
    14: "Ice Ring",
    15: "Lightning Ring",
    16: "Dark Ring",
    17: "White Ring",
    18: "Spirit Tears",
    19: "Moon Tears",
    20: "Rainbow Tears",
    21: "Sea Tears",
    22: "Spirit Particle",
    23: "Lore Particle",
    24: "Wish Particle",
    25: "Warped Particle",
    26: "Orichalcum",
    27: "Dark Matter",
    28: "Animaton",
    29: "Oxsecium",
    30: "Gungnir",
    31: "Masamune",
    32: "Apollo",
    33: "Asclepius",
    34: "Gae Bolg",
    35: "Excalibur",
    36: "Yumiharizuki",
    37: "Vajra",
    38: "Gaea",
    39: "Planet's Heart",
    40: "Flame of Indra",
    41: "Gyros",
    42: "Defender",
    43: "Phoenix",
    44: "Flamedrake Spear",
    45: "Maelstrom Bow",
    46: "Green Ring",
    47: "Terra Fragment",
    48: "Caladbolg",
    49: "Caladcholg",
    50: "Metal Ticket",
    51: "Cobalt Goblet",
    52: "Trident",
    53: "Time Extension",
    54: "Disarmer",
    55: "EXP Boost",
    56: "Coin Boost",
    57: "Amethyst Flame",
    58: "Rune",
    59: "The Emperor",
    60: "The Hierophant",
    61: "Knight of Swords",
    62: "Knight of Spears",
    63: "Knight of Bows",
    64: "Knight of Wands",
    65: "The Sun",
    66: "The Moon",
    67: "The Tower",
    68: "Judgment",
    69: "Knight of Chalices",
    70: "Knight of Pentacles",
    71: "Balmung",
    72: "Tyrfing",
    73: "Celestial Bow",
    74: "Naegling",
    75: "Varunastra",
    76: "Raikiri",
    77: "Codex Runicus",
    78: "Harpe",
    79: "Hotarumaru",
    80: "Energy",
    81: "Fellowship Ticket",
    82: "Wisp of Jealousy",
    83: "Cipher Cell",
    84: "Heartwood Sword",
    85: "Heartwood Spear",
    86: "Heartwood Bow",
    87: "Heartwood Wand",
    88: "Heartwood Pendant",
    89: "Mangled Horn",
    90: "Sentient Flame",
    91: "Lustrous Tail",
    92: "Ignorant Flea",
    93: "Deepwater Helix",
    94: "Mantle Helix",
    95: "Black Hole",
    96: "White Hole",
    97: "Wormhole",
    98: "Ether",
    99: "Elixir",
    100: "Jade Magatama",
    101: "Thunderbird Wing",
    102: "Crust Loop",
    103: "Mantle Loop",
    104: "Core Loop",
    105: "Tranquil Clock",
    106: "Tome of Enlightenment",
    107: "Lantern",
    108: "Compass",
    109: "Ancient Map",
    110: "Key of Hearts",
    111: "Key of Diamonds",
    112: "Companion Ticket",
    113: "Formless Clay",
    114: "Parchment",
    115: "Locket of Vows",
    116: "Slippery Sand",
    117: "Conceptual Canvas",
    118: "Dark Star",
    119: "Evanescent Star",
    120: "Shooting Star",
    121: "Binary Star",
    122: "Photon Ring",
    123: "Graviton Ring",
    124: "Animata Egg",
    125: "Animata Claw",
    126: "Animata Eye",
    127: "Animata Hair",
    128: "Animata Breath",
    129: "Animata Bone",
    130: "Animata Tail",
    131: "Animata Mustache",
    132: "Temporal Helix",
    133: "Pig Snout",
    134: "Bahamut's Fang",
    135: "Leviathan's Fang",
    136: "Odin's Fang",
    137: "Flawless Helix",
    138: "Ice Essence",
    139: "White Essence",
    140: "Star Crystal",
    141: "Bloody Coat of Arms",
    142: "Radiant Glory",
    143: "Mana Stone",
    144: "Magic Flute",
    145: "Necklace",
    146: "Illusion Flute",
    147: "Moggy's Sunglasses",
    148: "Nephrite Kudatama",
    149: "Blackbird Wing",
    150: "Smooth Sensation",
    151: "Drifting Horn",
    152: "Shiny Scale",
    153: "Stylish Hoof",
    154: "Leiden Potato",
    155: "Cleigne Wheat",
    156: "Garula Sirloin",
    157: "Garulessa Steak",
    158: "Dish and Chips",
    159: "Grease Monkey's Schnitzel Sandwich",
    160: "Garulessandwich",
    161: "Level Candy",
    162: "Skill Candy",
    163: "Luck Candy",
    164: "Solar Ring",
    165: "Lunar Ring",
    166: "Reinforcement Alika",
    167: "Reinforcement Gugba",
    168: "Mech Skill Drop",
    169: "Improvement Module",
    170: "Expansion Module",
    171: "Evolution Module",
    172: "Reinforcement Bajanna",
    173: "Seal of Favor",
    174: "Sacred Mirror",
    175: "Level Candybox",
    176: "Skill Candybox",
    177: "Luck Candybox",
    178: "Seal of Intimacy",
    179: "Nightbloom",
    180: "Reinforcement Zeera",
    181: "Animata Core",
}